### ISSUE TITLE
❗ [버그][Swagger] 서버환경에서 Swagger 접근 가능한 문제

### ISSUE THREAD

**Issue by Cassiiopeia** [Cassiiopeia/suh-project-utility#5]
🗒️ 설명
---

- 서버환경에서 Swagger 접속가능

🔄 재현 방법
---

1. 문제 동일

📸 참고 자료
---

<img width="436" alt="Image" src="https://github.com/user-attachments/assets/35c45610-31de-4aa6-bc5a-95237919a227" />

✅ 예상 동작
---

- Swagger를 빈 등록 해제하여서 사용할수없어야함

⚙️ 환경 정보
---

- **OS**: 맥
- **브라우저**: 크롬
- **기기**: 

🙋‍♂️ 담당자
---
- **백엔드**: @Cassiiopeia 
- **프론트엔드**: 이름
- **디자인**: 이름

**Comment by Cassiiopeia** [comment]
<img width="423" alt="Image" src="https://github.com/user-attachments/assets/3defee55-af21-4ebb-a40e-2adc935df318" />

다음과 같이 잘 차단됩니다

설정에서 다음을 설정하여서 서버환경일때 Swagger를 비활성화 시킵니다

```
# prod 환경일 경우
spring:
  config:
    activate:
      on-profile: prod

springdoc:
  swagger-ui:
    enabled: false
```
