### ISSUE TITLE
⚙️ [기능추가][우분투] 우분투 GUI 를 웹에서 사용할수있는 기능 추가

### ISSUE THREAD

**Issue by Cassiiopeia** [Cassiiopeia/suh-project-utility#6]
📝 현재 문제점
---

- 회사내에서 AI 도메인 차단에 대한 서버내부 간편한 우분투로 GUI 크롬을 통해 AI 서비스를 이용하는 방법이 필요합니다

🛠️ 해결 방안 / 제안 기능
---

- 요구사항: 이미지 , 텍스트 복사 붙여넣기가 되어야하고 AI URL이 차단되면안됨
- 경량화 우분투 크롬 실행 필요
- 웹에서 Xvfb 가상 디스플레이 를 실행해서 GUI 환경을 생성함
- 크롬 브라우저가 가상 디스플레이에서 실행됨
- NoVNC 서버가 Xvfb 화면을 웹 브라우저로 전송 ( 웹 브라우저에서 원격 크롬을 스트리밍합니다 )
- 영상송출 방식이므로 시놀로지에 부하가 좀 갑니다 (너무 시끄러워욬ㅋㅋㅋ ) 계속 시놀로지가 영상을 보내줘야해서 하드디스크에서 소리가 계속 나네요...
- 그래서 나중에 개선해보도록 하겠습니다. 그래서 업무시간에만 실행하고 끄는 그런 Docker 를 제어할수있는 토글 버튼이 필요할것같습니다
- 

항목 | NoVNC 스트리밍 | 일반 크롬 실행
-- | -- | --
방식 | Xvfb + NoVNC로 영상 송출 | 로컬 크롬 직접 실행
속도 | 네트워크 & GPU 성능에 따라 달라짐 | 로컬 성능에 영향
장점 | 가벼운 기기에서도 크롬 사용 가능 | 빠른 응답 속도
단점 | 고화질 영상 재생 시 부하 증가 | 원격 접속 불가

🙋‍♂️ 담당자
---
- 백엔드: @Cassiiopeia 
- 프론트엔드: 이름
- 디자인: 이름

**Comment by Cassiiopeia** [comment]
```
version: '3'
services:
  ubuntu-desktop:
    image: kasmweb/ubuntu-focal-desktop:1.13.0
    container_name: ubuntu-desktop
    environment:
      - VNC_PW=비밀번호
    ports:
      - "3006:6901"  # Kasm 웹 인터페이스
    volumes:
      - /volume1/docker/ubuntu-desktop/config:/config
    shm_size: '2gb'  # 메모리 증가
    restart: unless-stopped
```

해당 부분으로 작업하였었는데 너무 무거워서 사용하지않을시 종료해야합니다

시놀로지 하드디스크 소리가 너무시끄럽군요
